routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('regis','RegistrationController', ['middleware' => 'check']);

Route::resource('login','LoginController');

// Route::resource('product','ProductController', ['middleware' => 'checkLogout']);

// Route::resource('order','MyOrderController', ['middleware' => 'checkLogout']);

// Route::resource('logout','LogoutController', ['middleware' => 'checkLogout']);

// Route::resource('mypro','MyProfile', ['middleware' => 'checkLogout']);

// Route::resource('mypass','MyPassword', ['middleware' => 'checkLogout']);


Route::group(['middleware' => 'checkLogout'], function()
{
	Route::resource('product','ProductController');

    Route::resource('order','MyOrderController');

	Route::resource('logout','LogoutController');

	Route::resource('mypro','MyProfile');

    Route::resource('mypass','MyPassword');
});

resources/views/total/all-order-admin.blade.php
@extends('master')


    @section('title')
      ***admin page
    @endsection



    @section('content')  
                 <h2 class="first-heading text-center">**** Admin Page * </h2>

                   <div class="row">
                              <div class="col-md-8 col-sm-8">

          <p class="messsage"> {{ session('message') }} </p>

                     <h4><b> All Order : </b></h4> <hr>
                
                                            <div class="table-responsive">          
                                               <table class="table">
                                                  <thead>
                                       <tr>
                                        <th> order by </th> 
                                        <th> name </th>
                                        <th> price </th>
                                       </tr>
                                                    </thead>

                                                    <tbody>
                                                         
                                     @foreach($all_data as $data)
                                        <tr>
                                           <td> {{$data->getProfileName()}} </td>
                                           <td> {{$data->getProductName()}} </td>
                                           <td> {{$data->getProductPrice()}} </td>
                                            
                                        </tr>
                                   
                                     @endforeach 
                                                    </tbody>
                                                </table>
                                            </div> 
                                   {!!$all_data->render() !!} 

                              </div>
                              <div class="col-md-4 col-sm-4 sidebar ">
                               <nav class="navbar navbar-inverse ">
                                <div class="navbar-header">
                                  <ul>
                                    <li>
                                 <button type="button" class="btn btn-success navbar-toggle sidebar-btn" data-toggle="collapse" data-target="#myNavbar2">
                                      SIDEBAR
                                          
                                   </button>
                                 </li>
                               </ul>
                                </div>

                                <div class="collapse navbar-collapse" id="myNavbar2">
                                 <ul class="sidebar-ul">
                                    <li> <a href="{{route('login.create')}}"><button type="button" class="btn btn-primary"> Home </button> </a> </li>

                                    <li> <a href="{{route('product.create')}}"><button type="button" class="btn btn-primary"> Add New Product </button> </a> </li> 

                                     <li> <a href="{{route('product.index')}}"><button type="button" class="btn btn-primary">  All Product </button> </a> </li>

                                     <li> <a href="{{route('login.index')}}"><button type="button" class="btn btn-primary"> Our Member </button></a> </li> 

                                     <li> <a href="{{route('order.index')}}"><button type="button" class="btn btn-primary"> Order a Product </button></a> </li>

                                     <li> <a href="{{route('order.create')}}"><button type="button" class="btn btn-primary"> All Order </button></a> </li>

                                     <li> <a href="{{route('logout.index')}}"><button type="button" class="btn btn-primary"> Logout </button></a> </li>

                                      <li> <a href="{{route('mypro.index')}}"><button type="button" class="btn btn-primary"> My Profile </button></a> </li>

                                      <li> <a href="{{route('mypass.index')}}"><button type="button" class="btn btn-primary"> Change Password </button></a> </li>

                                      
                                   
                                 </ul>  
                                 </div>  
                                 </nav> 
                              </div>           <!-- col-md-4 col-sm-4 -->
                   </div>

    @endsection

resources/views/total/change-password-admin.blade.php
@extends('master')


    @section('title')
      change ur password
    @endsection



    @section('content')  
                 <h2 class="first-heading text-center">**** Admin Page * </h2>

                   <div class="row">
                              <div class="col-md-8 col-sm-8">
                                  
                                 <h1 class="text-center"> change your password </h1>     
                                       
                                              @if ($errors->any())
                                                   <div class="alert alert-danger">
                                                       <ul>
                                                           @foreach ($errors->all() as $error)
                                                               <li>{{ $error }}</li>
                                                           @endforeach
                                                       </ul>
                                                    </div>
                                               @endif


                  <p class="messsage text-center" style="color:red"> {{ session('message') }} </p>        


                    {!! Form::open(['route' => ['mypass.update', $data->id],'method' => 'put']) !!}
                                 <div class="form-group row">
                                         <div class="col-md-3 col-sm-3 col-xs-3">
                                             <label class="contrl-label" for="old_pass"> Old Password:</label>
                                         </div>
                                         <div class="col-md-9 col-sm-9 col-xs-9">
                                             <input type="password" class="form-control" name="old_pass" required>
                                         </div>
                                 </div>

                                  <div class="form-group row">
                                         <div class="col-md-3 col-sm-3 col-xs-3">
                                             <label class="control-label" for="new_pass1">New Password: </label>
                                         </div>
                                         <div class="col-md-9 col-sm-9 col-xs-9">
                                              <input type="password" class="form-control" name="new_pass1" required> 
                                         </div>
                                  </div>

                                  <div class="form-group row">
                                         <div class="col-md-3 col-sm-3 col-xs-3">
                                             <label class="control-label" for="password">Confirm Password: </label>
                                         </div>
                                         <div class="col-md-9 col-sm-9 col-xs-9">
                                              <input type="password" class="form-control" name="password" required> 
                                         </div>
                                  </div>

                                  <input class="btn btn-success" type="submit" value="Submit">
                         {!! Form::close() !!}                                   
                           





                              </div>
                              <div class="col-md-4 col-sm-4 sidebar ">
                               <nav class="navbar navbar-inverse ">
                                <div class="navbar-header">
                                  <ul>
                                    <li>
                                 <button type="button" class="btn btn-success navbar-toggle sidebar-btn" data-toggle="collapse" data-target="#myNavbar2">
                                      SIDEBAR
                                          
                                   </button>
                                 </li>
                               </ul>
                                </div>

                                <div class="collapse navbar-collapse" id="myNavbar2">
                                 <ul class="sidebar-ul">
                                    <li> <a href="{{route('login.create')}}"><button type="button" class="btn btn-primary"> Home </button> </a> </li>

                                    <li> <a href="{{route('product.create')}}"><button type="button" class="btn btn-primary"> Add New Product </button> </a> </li> 

                                     <li> <a href="{{route('product.index')}}"><button type="button" class="btn btn-primary">  All Product </button> </a> </li>

                                     <li> <a href="{{route('login.index')}}"><button type="button" class="btn btn-primary"> Our Member </button></a> </li> 

                                     <li> <a href="{{route('order.index')}}"><button type="button" class="btn btn-primary"> Order a Product </button></a> </li>

                                     <li> <a href="{{route('order.create')}}"><button type="button" class="btn btn-primary"> All Order </button></a> </li>

                                     <li> <a href="{{route('logout.index')}}"><button type="button" class="btn btn-primary"> Logout </button></a> </li>

                                      <li> <a href="{{route('mypro.index')}}"><button type="button" class="btn btn-primary"> My Profile </button></a> </li>

                                      <li> <a href="{{route('mypass.index')}}"><button type="button" class="btn btn-primary"> Change Password </button></a> </li>

                                      
                                   
                                 </ul>  
                                 </div>  
                                 </nav> 
                              </div>           <!-- col-md-4 col-sm-4 -->
                   </div>

    @endsection

resources/views/total/edit-profile-admin.blade.php
@extends('master')


    @section('title')
      ***edit profile
    @endsection



    @section('content')  
                 <h2 class="first-heading text-center">**** Admin Page * </h2>

                   <div class="row">
                              <div class="col-md-8 col-sm-8">
                                  <h1 class="text-center"> Edit Your Profile </h1>
                                      
                                                  @if ($errors->any())
                                                       <div class="alert alert-danger">
                                                           <ul>
                                                               @foreach ($errors->all() as $error)
                                                                   <li>{{ $error }}</li>
                                                               @endforeach
                                                           </ul>
                                                        </div>
                                                   @endif


                 <p class="messsage text-center" style="color:red;"> {{ session('message') }} </p>        


                                  {!! Form::open(['route' => ['mypro.update', $data->id],'method' => 'put','files' => true]) !!}
                                               <div class="form-group row">
                                                       <div class="col-md-3 col-sm-3 col-xs-3">
                                                           <label class="contrl-label" for="name"> Name:</label>
                                                       </div>
                                                       <div class="col-md-9 col-sm-9 col-xs-9">
                                                           <input type="text" class="form-control" name="name"  value="{{ ($data->name) }}" required>
                                                       </div>
                                               </div>

                                                <div class="form-group row">
                                                       <div class="col-md-3 col-sm-3 col-xs-3">
                                                           <label class="control-label" for="address">Email: </label>
                                                       </div>
                                                       <div class="col-md-9 col-sm-9 col-xs-9">
                                                            <input type="email" class="form-control" name="address"  value="{{ ($data->email) }}" readonly> 
                                                       </div>
                                                </div>

                                                 <div class="form-group row">
                                                       <div class="col-md-3 col-sm-3 col-xs-3">
                                                            <label class="control-label" for="image">Image: </label>
                                                        </div>
                                                        <div class="col-md-9 col-sm-9 col-xs-9">
                                                             <input type="file" class="form-control" name="image" id="image"> 
                                                        </div>
                                                  </div>

                                                <input class="btn btn-success" type="submit" value="Submit">
                                       {!! Form::close() !!}
                                                     


                              </div>
                              <div class="col-md-4 col-sm-4 sidebar ">
                               <nav class="navbar navbar-inverse ">
                                <div class="navbar-header">
                                  <ul>
                                    <li>
                                 <button type="button" class="btn btn-success navbar-toggle sidebar-btn" data-toggle="collapse" data-target="#myNavbar2">
                                      SIDEBAR
                                          
                                   </button>
                                 </li>
                               </ul>
                                </div>

                                <div class="collapse navbar-collapse" id="myNavbar2">
                                 <ul class="sidebar-ul">
                                    <li> <a href="{{route('login.create')}}"><button type="button" class="btn btn-primary"> Home </button> </a> </li>

                                    <li> <a href="{{route('product.create')}}"><button type="button" class="btn btn-primary"> Add New Product </button> </a> </li> 

                                     <li> <a href="{{route('product.index')}}"><button type="button" class="btn btn-primary">  All Product </button> </a> </li>

                                     <li> <a href="{{route('login.index')}}"><button type="button" class="btn btn-primary"> Our Member </button></a> </li> 

                                     <li> <a href="{{route('order.index')}}"><button type="button" class="btn btn-primary"> Order a Product </button></a> </li>

                                     <li> <a href="{{route('order.create')}}"><button type="button" class="btn btn-primary"> All Order </button></a> </li>

                                     <li> <a href="{{route('logout.index')}}"><button type="button" class="btn btn-primary"> Logout </button></a> </li>

                                      <li> <a href="{{route('mypro.index')}}"><button type="button" class="btn btn-primary"> My Profile </button></a> </li>

                                      <li> <a href="{{route('mypass.index')}}"><button type="button" class="btn btn-primary"> Change Password </button></a> </li>

                                      
                                   
                                 </ul>  
                                 </div>  
                                 </nav> 
                              </div>           <!-- col-md-4 col-sm-4 -->
                   </div>

    @endsection

resources/views/total/my-order-admin.blade.php
@extends('master')


    @section('title')
      ***order
    @endsection



    @section('content')  
                 <h2 class="first-heading text-center">**** Admin Page * </h2>

                   <div class="row">
                              <div class="col-md-8 col-sm-8">
                                  <p class="messsage text-center"> {{ session('message') }} </p> 
                                      
                                         <div class="table-responsive">          
                                            <table class="table">
                                                <thead>
                                   <tr>
                                    <th> IMAGE </th>
                                    <th> PRODUCT NAME </th> 
                                    <th> PRICE </th>
                                    <th> ADD TO CHART </th>
                                  
                                   </tr>
                                                 </thead>

                                                 <tbody>
                                                       
                                 @foreach($alldata as $data)
                                    <tr>
                                       <td> 
                                         <img src="{{ asset('storage/products/'.$data->file_name)}}" alt="product" class="product-img img-responsive">
                                       </td>
                                       <td> {{$data->product_name}} </td>
                                       <td> {{$data->price}} </td>
                                       <td>  <button type="button" class="btn btn-primary"><a href="{{route('order.edit',$data->id)}}"> add to chart</a></button></td>
                                      
                                       
                                    </tr>
                                
                                 @endforeach 
                                                 </tbody>
                                             </table>
                                         </div>   
                                         {!!$alldata->render() !!}                
                                   

                              </div>

                    <div class="col-md-4 col-sm-4 sidebar ">
                     <nav class="navbar navbar-inverse ">
                      <div class="navbar-header">
                        <ul>
                          <li>
                       <button type="button" class="btn btn-success navbar-toggle sidebar-btn" data-toggle="collapse" data-target="#myNavbar2">
                            SIDEBAR
                                
                         </button>
                       </li>
                     </ul>
                      </div>

                      <div class="collapse navbar-collapse" id="myNavbar2">
                       <ul class="sidebar-ul">
                          <li> <a href="{{route('login.create')}}"><button type="button" class="btn btn-primary"> Home </button> </a> </li>

                          <li> <a href="{{route('product.create')}}"><button type="button" class="btn btn-primary"> Add New Product </button> </a> </li> 

                           <li> <a href="{{route('product.index')}}"><button type="button" class="btn btn-primary">  All Product </button> </a> </li>

                           <li> <a href="{{route('login.index')}}"><button type="button" class="btn btn-primary"> Our Member </button></a> </li> 

                           <li> <a href="{{route('order.index')}}"><button type="button" class="btn btn-primary"> Order a Product </button></a> </li>

                           <li> <a href="{{route('order.create')}}"><button type="button" class="btn btn-primary"> All Order </button></a> </li>

                           <li> <a href="{{route('logout.index')}}"><button type="button" class="btn btn-primary"> Logout </button></a> </li>

                            <li> <a href="{{route('mypro.index')}}"><button type="button" class="btn btn-primary"> My Profile </button></a> </li>

                            <li> <a href="{{route('mypass.index')}}"><button type="button" class="btn btn-primary"> Change Password </button></a> </li>

                            
                         
                       </ul>  
                       </div>  
                       </nav> 
                    </div>           <!-- col-md-4 col-sm-4 -->
                   </div>

    @endsection

resources/views/total/my-profile-admin.blade.php
@extends('master')


    @section('title')
      ***profile
    @endsection



    @section('content')  
                 <h2 class="first-heading text-center">**** Admin Page * </h2>

                   <div class="row">
                              <div class="col-md-8 col-sm-8">
           <p class="messsage" style="color:green"> {{ session('message') }} </p>                      
        

                                @foreach($all_data as $data)            
                                  <div class="row">
                                     <div class="col-sm-6">
        <img src="{{ asset('storage/upload/'.$data->file_name)}}" alt="user profile" class="pro-img img-responsive">
                                     </div>
                                     <div class="col-sm-6">
                                         <div class="table-responsive">          
                                            <table class="table tab-padding">
                                                
                                             
                                           <tr>
                                             <th>  NAME    </th> 
                                             <td > {{$data->name}} </td> 
                                           </tr>
                                           <tr>
                                             <th>  EMAIL    </th> 
                                             <td> {{$data->email}} </td> 
                                           </tr>
                                           <tr>
                                             <th>  ACTION     </th> 
                                             <td> <button type="button" class="btn btn-primary"><a href="{{route('mypro.edit',$data->id)}}"> click for edit</a></button></td> 
                                           </tr>
                                                </table>
                                                       
                                          </div>  
                                     </div>
                                  </div> 
                                  @endforeach    

                                          
                                                     


                              </div>
                        <div class="col-md-4 col-sm-4 sidebar ">
                         <nav class="navbar navbar-inverse ">
                          <div class="navbar-header">
                            <ul>
                              <li>
                           <button type="button" class="btn btn-success navbar-toggle sidebar-btn" data-toggle="collapse" data-target="#myNavbar2">
                                SIDEBAR
                                    
                             </button>
                           </li>
                         </ul>
                          </div>

                          <div class="collapse navbar-collapse" id="myNavbar2">
                           <ul class="sidebar-ul">
                              <li> <a href="{{route('login.create')}}"><button type="button" class="btn btn-primary"> Home </button> </a> </li>

                              <li> <a href="{{route('product.create')}}"><button type="button" class="btn btn-primary"> Add New Product </button> </a> </li> 

                               <li> <a href="{{route('product.index')}}"><button type="button" class="btn btn-primary">  All Product </button> </a> </li>

                               <li> <a href="{{route('login.index')}}"><button type="button" class="btn btn-primary"> Our Member </button></a> </li> 

                               <li> <a href="{{route('order.index')}}"><button type="button" class="btn btn-primary"> Order a Product </button></a> </li>

                               <li> <a href="{{route('order.create')}}"><button type="button" class="btn btn-primary"> All Order </button></a> </li>

                               <li> <a href="{{route('logout.index')}}"><button type="button" class="btn btn-primary"> Logout </button></a> </li>

                                <li> <a href="{{route('mypro.index')}}"><button type="button" class="btn btn-primary"> My Profile </button></a> </li>

                                <li> <a href="{{route('mypass.index')}}"><button type="button" class="btn btn-primary"> Change Password </button></a> </li>

                                
                             
                           </ul>  
                           </div>  
                           </nav> 
                        </div>           <!-- col-md-4 col-sm-4 -->
                   </div>

    @endsection

resources/views/total/registration.blade.php
@extends('master')


    @section('title')
      welcome for registration here
    @endsection



    @section('content')  
 	  	         <h2 class="first-heading text-center"> Welcome to Registration Here:: </h2>

          <p class="messsage text-center"> {{ session('message') }} </p>

                    

                    @if ($errors->any())
                         <div class="alert alert-danger">
                             <ul>
                                 @foreach ($errors->all() as $error)
                                     <li>{{ $error }}</li>
                                 @endforeach
                             </ul>
                         </div>
                     @endif



 	  	        
 	  	         {!! Form::open(array('route'=>'regis.store','files' => true)) !!}
                        <div class="form-group row">
                               <div class="col-md-3 col-sm-3 col-xs-3">
                                   <label class="contrl-label" for="name">Name:</label>
                               </div>
                               <div class="col-md-9 col-sm-9 col-xs-9">
                                    <input type="text" class="form-control" name="name"  value="{{ old('name') }}" required>
                                </div>
                         </div>


                         <div class="form-group row">
                                <div class="col-md-3 col-sm-3 col-xs-3">
                                     <label class="control-label" for="email">Email: </label>
                                 </div>
                                 <div class="col-md-9 col-sm-9 col-xs-9">
                                      <input type="email" class="form-control" name="email"  value="{{ old('email') }}" required> 
                                 </div>
                         </div>


                         <div class="form-group row">
                                <div class="col-md-3 col-sm-3 col-xs-3">
                                     <label class="control-label" for="password">Password: </label>
                                 </div>
                                 <div class="col-md-9 col-sm-9 col-xs-9">
                                      <input type="password" class="form-control" name="password"  value="{{ old('password') }}" required> 
                                 </div>
                         </div>


                          <div class="form-group row">
                                 <div class="col-md-3 col-sm-3 col-xs-3">
                                      <label class="control-label" for="password2">Password(again): </label>
                                  </div>
                                  <div class="col-md-9 col-sm-9 col-xs-9">
                                       <input type="password" class="form-control" name="password2"  value="{{ old('password2') }}" required> 
                                  </div>
                          </div>


                           <div class="form-group row">
                                 <div class="col-md-3 col-sm-3 col-xs-3">
                                      <label class="control-label" for="image">Image: </label>
                                  </div>
                                  <div class="col-md-9 col-sm-9 col-xs-9">
                                       <input type="file" class="form-control" name="image" id="image"> 
                                  </div>
                           </div>
 
                         <input class="btn btn-success" type="submit" value="Submit">
 	  	          {!! Form::close() !!} 


       

    @endsection